### ISSUE TITLE
Updated plugin to include new material icons

### ISSUE THREAD

**Issue by ghost** [interisti/material-icons-generator-plugin#4]
The material icons repo is updated with tons of new icons. Ideally it should be pulled dynamically from the repo so you don't need to update the plugin.

**Comment by interisti** [comment]
right, i will make changes, thanks for your comment

**Comment by interisti** [comment]
Hi @robertbaker ,
I've made necessary changes, you can check new version in releases section or download from here: https://github.com/interisti/material-icons-generator-plugin/releases/download/v1.0/MaterialIconsGenerator.material-icons-generator-plugin_1.0.mpack
